### ISSUE TITLE
Running tests gives an empty out put

### ISSUE THREAD

**Issue by AutomatedTester** [vaibhavsingh97/nightwatchjs-schematics#3]
When creating a new project(version numbers below) I could not get the tests to do anything.

STR:
1. `ng new angular-nightwatch`
2. `cd angular-nightwatch` (Note there is no e2e as a default)
3.  `mkdir e2e` and then follow https://medium.com/swlh/angular-end-to-end-testing-with-protractor-55897de591be for making test files
4. `ng add @nightwatch/schematics` and select the defaults
5. `ng e2e`

When I run 5. I now get 3 empty lines output. It looks like Geckodriver is starting but then never getting the new session command but it's hard to see as there is nothing output from Nightwatch

```bash
davidburns in ~/development/bsol λ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.4
Node: 14.16.1
Package Manager: npm 7.11.2
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.4 (cli-only)
@angular-devkit/core         12.0.4 (cli-only)
@angular-devkit/schematics   12.0.4 (cli-only)
@schematics/angular          12.0.4 (cli-only)```

**Comment by vaibhavsingh97** [comment]
Thanks for raising the issue 🙌 , I am able to reproduce the issue at my end
