### ISSUE TITLE
ng add @nightwatch/schematics errors if no e2e directory (which is the default)

### ISSUE THREAD

**Issue by AutomatedTester** [vaibhavsingh97/nightwatchjs-schematics#4]
When there is no `e2e` directory the adding of schematics, and the code it runs, errors.

STR:
1. `ng new angular-nightwatch`
2. `cd angular-nightwatch` 
3. `ng add @nightwatch/schematics`

It will complain there is no e2e directory. It might be good to have better messaging here if we can

**Comment by vaibhavsingh97** [comment]
> It might be good to have better messaging here if we can

Sure, I guess I should have warned that user with a better message, something like this
```
Warning: skip deleting, e2e/ directory does not exist
```
